# Autogenerated wrapper script for MrBayes_jll for x86_64-w64-mingw32-mpi+microsoftmpi
export mb, mb_MPI

using CompilerSupportLibraries_jll
using MicrosoftMPI_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("MrBayes")
JLLWrappers.@declare_executable_product(mb)
JLLWrappers.@declare_executable_product(mb_MPI)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        mb,
        "bin\\mb.exe",
    )

    JLLWrappers.@init_executable_product(
        mb_MPI,
        "bin\\mb_MPI.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
