# Autogenerated wrapper script for MrBayes_jll for x86_64-w64-mingw32
export mb, mb_MPI

using MicrosoftMPI_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("MrBayes")
JLLWrappers.@declare_executable_product(mb)
JLLWrappers.@declare_executable_product(mb_MPI)
function __init__()
    JLLWrappers.@generate_init_header(MicrosoftMPI_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        mb,
        "bin\\mb.exe",
    )

    JLLWrappers.@init_executable_product(
        mb_MPI,
        "bin\\mb_MPI.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
