# Autogenerated wrapper script for MrBayes_jll for x86_64-unknown-freebsd
export mb, mb_MPI

using MPICH_jll
using LLVMOpenMP_jll
using Readline_jll
JLLWrappers.@generate_wrapper_header("MrBayes")
JLLWrappers.@declare_executable_product(mb)
JLLWrappers.@declare_executable_product(mb_MPI)
function __init__()
    JLLWrappers.@generate_init_header(MPICH_jll, LLVMOpenMP_jll, Readline_jll)
    JLLWrappers.@init_executable_product(
        mb,
        "bin/mb",
    )

    JLLWrappers.@init_executable_product(
        mb_MPI,
        "bin/mb_MPI",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
